/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UserDll */

#ifndef _Included_UserDll
#define _Included_UserDll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     UserDll
 * Method:    Add1
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_UserDll_Add1(JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
